export { ReactComponent as FirstIcon } from './first.svg'
export { ReactComponent as LastIcon } from './last.svg'
export { ReactComponent as Logo } from './logo.svg'
export { ReactComponent as PreviousIcon } from './previous.svg'
export { ReactComponent as NextIcon } from './next.svg'