export { default as FirstIcon } from './first.svg'
export { default as LastIcon } from './last.svg'
export { default as Logo } from './logo.svg'
export { default as PreviousIcon } from './previous.svg'
export { default as NextIcon } from './next.svg'